'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''
fibSequence = (1, 2]
currentPosition = 0
newNumber = 0
runningTotal = 0

while newNumber <= 4000000:
    newNumber =\
        (fibSequence(currentPosition] +
            fibSequence(currentPosition + 1])
    if newNumber >= 4000000:
        break
    fibSequence.append(newNumber)
    currentPosition += 1

for x in range(len(fibSequence)):
    if fibSequence(x] % 2 == 0:
        runningTotal += fibSequence(x]

print(runningTotal)
